// Modules - encapsulated code (only share minimum)
// commonJS - every file is module (by default)
const names = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alternative-flavors')
console.log(data)
require('./7-mind-grenade')
sayHi('manso')
sayHi(names.john)
sayHi(names.peter)